import BackToTop from "../components/BackToTop";
import { Accordion, Card, Chip } from "@heroui/react";
import { buttonVariants } from "@heroui/react";
import Footer from "../components/Footer";
import PageHero from "../components/PageHero";
import PdfViewer from "../components/PdfViewer";
import Reveal from "../components/Reveal";

export const metadata = {
  title: "HyperXion - Rocket",
};

const JUMP_LINKS = [
  { href: "#RPB", label: "Rocket Propulsion ⬇️" },
  { href: "#HR", label: "Hybrid Rocket ⬇️" },
  { href: "#RSS", label: "Rocket Science For Students ⬇️" },
];

const QUICK_FACTS = [
  {
    title: "🚀 Basic Principles",
    body: (
      <>
        <p>
          Newton&apos;s Third Law: &ldquo;For every action, there is an
          equal and opposite reaction.&rdquo; Rockets expel mass (exhaust
          gases) in one direction to move in the opposite direction.
        </p>
        <p className="mt-3">
          Thrust: The force that propels a rocket upward, generated by the
          expulsion of exhaust gases from the engine.
        </p>
        <p className="mt-3">
          Gravity &amp; Drag: Rockets must overcome Earth&rsquo;s gravity
          and air resistance to reach space.
        </p>
      </>
    ),
  },
  {
    title: "🧪 Core Components",
    body: (
      <>
        <img
          src="/Rocket/rcd.jpg"
          alt="Rocket components"
          className="mx-auto mb-4 w-full max-w-[320px] rounded-2xl"
        />
        <p>
          Propulsion Systems: Typically chemical rockets that burn fuel and
          oxidizer to create thrust. These can be liquid-fueled (e.g.,
          SpaceX&rsquo;s Falcon 9), solid-fueled (used in missiles and
          boosters), or hybrid / electric / ion propulsion (used for
          deep-space missions).
        </p>
        <p className="mt-3">
          Guidance and Control: Involves computers, gyroscopes, sensors, and
          algorithms that ensure the rocket follows the intended path.
        </p>
        <p className="mt-3">
          Aerodynamics: Study of how air flows around the rocket; important
          during launch when passing through the atmosphere.
        </p>
        <p className="mt-3">
          Structures and Materials: Rockets must be lightweight but
          extremely strong to withstand high pressure, temperature, and
          acceleration forces.
        </p>
      </>
    ),
  },
  {
    title: "📐 Key Equations",
    body: (
      <>
        <p>● Tsiolkovsky Rocket Equation:</p>
        <img
          src="/Rocket/law.png"
          alt="Rocket equation"
          className="mx-auto my-4 w-full max-w-[220px]"
        />
        <p>
          Where: Δv = change in velocity, ve = exhaust velocity, m0 = initial
          mass, mf = final mass (after fuel is burned).
        </p>
        <p className="mt-3">
          This tells us how much a rocket can accelerate based on how much
          mass it can shed as fuel.
        </p>
      </>
    ),
  },
  {
    title: "🌌 Challenges",
    body: (
      <>
        <p>
          Weight vs. Fuel: More fuel means more weight, which in turn
          requires more fuel&mdash;a difficult trade-off.
        </p>
        <p className="mt-3">
          Extreme Conditions: Temperatures, pressures, and forces are
          intense; small errors can lead to mission failure.
        </p>
        <p className="mt-3">
          Precision: Orbital mechanics require very precise calculations and
          timing.
        </p>
      </>
    ),
  },
  {
    title: "🛰️ Applications",
    body: (
      <>
        <p>● Launching satellites</p>
        <p className="mt-3">
          ● Space exploration (e.g., Mars rovers, moon landings)
        </p>
        <p className="mt-3">● Military defense systems</p>
        <p className="mt-3">
          ● Commercial space travel (e.g. HyperXion, SpaceX, Blue Origin)
        </p>
      </>
    ),
  },
];

const PROPULSION_BOOKS = [
  {
    title: "Aerospace Propulsion",
    pdf: "/Rocket/Propulsion Engineering/ap1.pdf",
    caption: "Aerospace Propulsion Book",
    text: `Aerospace propulsion is the study and technology of generating thrust to move vehicles through the atmosphere and into space. In aircraft, engines like turbojets, turbofans, and turboprops draw in air from the atmosphere, compress it, mix it with fuel, and ignite it to produce thrust. These are known as air-breathing engines and are efficient within the Earth's atmosphere. For spacecraft and rockets, propulsion relies on engines that carry both fuel and oxidizer, since there's no atmospheric oxygen in space. These include solid, liquid, and hybrid rockets. In both air and space propulsion systems, principles from thermodynamics, fluid dynamics, and Newton's laws of motion govern how energy is converted into motion.

Aerospace propulsion also involves managing extreme conditions—like high temperatures, pressures, and vibrations—requiring advanced materials such as titanium alloys, carbon composites, and ceramic coatings. There is also growing interest in reusable propulsion systems, like the ones developed by SpaceX and Blue Origin, which aim to reduce launch costs and increase flight frequency.`,
  },
  {
    title: "Aerothermodynamics of Gas Turbine and Rocket Propulsion",
    pdf: "/Rocket/Propulsion Engineering/ap3.pdf",
    caption: "Aerothermodynamics of Gas turbine and Rocket propulsion Book",
    text: `Involves the study of how energy is transferred and transformed within moving gases, focusing on the thermodynamic, fluid dynamic, and aerodynamic behavior of the working fluid inside engines. In gas turbines, air enters at high speed and is compressed, mixed with fuel, and combusted, and the resulting hot gases expand through a turbine before producing thrust through a nozzle.

In rocket propulsion, aerothermodynamics becomes more focused on high-speed, compressible flow and heat transfer in near-vacuum or high-altitude conditions. Rocket engines operate under much more extreme conditions than gas turbines, often exceeding temperatures of 3,000 Kelvin and requiring careful thermal management and nozzle design.`,
  },
  {
    title: "Design Of Liquid Propellant Rocket Engines",
    pdf: "/Rocket/Propulsion Engineering/ap4.pdf",
    caption: "Design Of Liquid Propellant Rocket Engines Book",
    text: `A liquid propellant rocket engine operates by burning liquid fuel and oxidizer to produce thrust. These two propellants are stored separately in tanks and are either pushed into the combustion chamber by high-pressure gas or by turbopumps. Inside the chamber, the propellants are mixed and ignited, and the resulting gases are expelled through a nozzle according to Newton's third law.

Liquid propellants can be either bipropellant (a separate fuel and oxidizer like kerosene and liquid oxygen) or monopropellant (a single chemical like hydrazine). Overall, liquid rocket engines are complex but highly controllable, making them ideal for both launch vehicles and spacecraft maneuvering.`,
  },
  {
    title: "Elements of Propulsion, Gas Turbines and Rockets",
    pdf: "/Rocket/Propulsion Engineering/ap9.pdf",
    caption: "Elements of Propulsion, Gas Turbines and Rockets Book",
    text: `Focuses on how engines generate thrust to move aircraft and spacecraft. Gas turbines are widely used in aircraft and operate by drawing in air, compressing it, mixing it with fuel, and igniting the mixture. Rockets, on the other hand, carry both fuel and oxidizer, allowing them to operate in space where atmospheric oxygen is absent.

Rocket propulsion is essentially brute force turned elegant—achieved by finely tuned combustion, high-pressure chambers, and nozzles engineered to expand gas with extreme precision, often using a convergent-divergent (De Laval) design to maximize exhaust velocity.`,
  },
  {
    title: "Fundamental Concepts of Liquid-Propellant Rocket Engines",
    pdf: "/Rocket/Propulsion Engineering/ap11.pdf",
    caption: "Fundamental Concepts of Liquid-Propellant Rocket Engines Book",
    text: `Revolves around harnessing chemical energy through controlled combustion to produce thrust. A key principle is Newton's third law: the expulsion of gases at high velocity creates the reactive force that lifts the rocket. Performance is largely measured by specific impulse, which shows how efficiently the engine uses propellant.

Unlike solid rockets, liquid engines can be throttled, shut down, or restarted, giving them greater flexibility and control — essential for precise maneuvers, orbital insertions, and deep space missions.`,
  },
  {
    title: "Liquid Rocket Propulsion",
    pdf: "/Rocket/Propulsion Engineering/ap25.pdf",
    caption: "Liquid Rocket Propulsion Book",
    text: `A method of generating thrust by burning liquid fuel with a liquid oxidizer in a combustion chamber to produce high-speed exhaust gases. One defining characteristic is its high degree of control — liquid engines can be throttled, shut down, and restarted during flight, making them ideal for missions requiring precise maneuvering.

There are different cycles used to drive the turbopumps in liquid engines, such as gas-generator, staged combustion, and expander cycles, each with trade-offs in complexity, efficiency, and thrust capability.`,
  },
  {
    title: "Rocket and Spacecraft Propulsion",
    pdf: "/Rocket/Propulsion Engineering/ap30.pdf",
    caption: "Rocket and Spacecraft Propulsion Book",
    text: `The science and engineering of moving vehicles through space or Earth's atmosphere by expelling mass to generate thrust. In space, propulsion relies entirely on Newton's third law — thrust is produced by ejecting high-speed particles in the opposite direction of desired motion.

Once in space, spacecraft often use more efficient propulsion systems such as ion thrusters or Hall-effect thrusters depending on mission needs, prioritizing efficiency over raw power for long-duration missions.`,
  },
  {
    title: "Rocket Propulsion Elements 1st",
    pdf: "/Rocket/Propulsion Engineering/ap31.pdf",
    caption: "Rocket Propulsion Elements 1st Book",
    text: `Rocket propulsion has its roots in ancient inventions, beginning with gunpowder-filled tubes used as military rockets in China around the 13th century. In the early 20th century, pioneers like Konstantin Tsiolkovsky, Robert Goddard, and Hermann Oberth transformed rocketry from speculative theory into a field grounded in physics and engineering.

By mid-century, rocket propulsion became central to global technological rivalry, leading to powerful launch vehicles like the Saturn V, which took humans to the Moon.`,
  },
  {
    title: "Rocket Propulsion Elements Eighth Edition",
    pdf: "/Rocket/Propulsion Engineering/ap40.pdf",
    caption: "Rocket Propulsion Elements Eighth Edition Book",
    text: `Explores rocket propulsion as a complex, multidisciplinary system that transforms stored chemical or electrical energy into directed motion through the expulsion of mass. It covers various propulsion types — chemical, liquid, solid, hybrid, and electric — each governed by distinct physical and operational principles.

Propulsion is revealed not as a single device, but as a chain of interacting systems that must function in harmony, from the tanks and feed lines to the nozzle exit, all under extreme thermal and pressure conditions.`,
  },
];

const HYBRID_BOOKS = [
  {
    title: "Fundamentals of Hybrid Rocket Combustion and Propulsion",
    pdf: "/Rocket/Hybird Rocket/HR1.pdf",
    caption: "Fundamentals of Hybrid Rocket Combustion and Propulsion Book",
    text: `A hybrid rocket combines elements of both solid and liquid rockets, using a solid fuel and a liquid or gaseous oxidizer. The combustion occurs at the surface of the solid fuel as the oxidizer flows over it, producing hot gases that are expelled through a nozzle to generate thrust.

Because the fuel is solid and inert on its own, hybrid rockets are generally safer to store and handle than fully liquid systems. They represent a middle ground in propulsion — offering greater control than solids and less complexity than liquids, often used in experimental, suborbital, or educational missions.`,
  },
];

const STUDENT_BOOKS = [
  {
    title: "Rocket Science For Student First Edition",
    pdf: "/Rocket/For school Students/RS1.pdf",
    caption: "Rocket Science For Student First Edition Book",
    text: `Rocket science is really just about understanding how things move, especially when trying to get something off Earth and into space. One of the most important ideas is Newton's third law — rockets push gas out of their engines really fast, and that pushes the rocket in the opposite direction.

Most rockets use staging: they're built in parts, and as each part runs out of fuel, it gets dropped off, so the rocket gets lighter and can go even faster. When a rocket goes fast enough sideways, it doesn't fall back down — that's how it gets into orbit.`,
  },
  {
    title: "Rocket Science For Student Second Edition",
    pdf: "/Rocket/For school Students/RS2.pdf",
    caption: "Rocket Science For Student Second Edition Book",
    text: `Once past the beginner stage, rocket science starts to feel less like magic and more like an intense form of physics and engineering. One of the most important ideas is the rocket equation — it shows the relationship between how much fuel you carry and how fast you can go, and as the rocket burns fuel, its changing mass affects everything.

Once in space, navigation relies on orbital mechanics — getting into orbit means going sideways fast enough that the planet curves away beneath you. It's a game of trade-offs: between power and weight, precision and complexity, cost and reliability.`,
  },
  {
    title: "Rocket Manual for Amateurs",
    pdf: "/Rocket/For school Students/RMA.pdf",
    caption: "Rocket Manual for Amateurs Book",
    text: `A fascinating little book that gives a glimpse into how early hobbyists and enthusiasts approached rocketry before it became the highly regulated, high-tech industry it is today. Written in the 1960s by David Sleeter, it walks through how to build your own rocket engines, mix propellants, and design launch systems using materials you could find at a hardware store.

Today, much of what's in the book would be considered dangerous or even illegal without proper permits — but as a historical artifact and learning tool, it still inspires the spirit of raw experimentation.`,
  },
];

function BookRow({ book, reversed }) {
  return (
    <Reveal>
      <Card
        variant="secondary"
        className="grid gap-6 p-6 md:grid-cols-2 md:p-8"
      >
        <div
          className={`flex flex-col justify-center ${
            reversed ? "md:order-2" : undefined
          }`}
        >
          <h3 className="text-xl font-bold text-foreground md:text-2xl">
            {book.title}
          </h3>
          {book.text.split("\n\n").map((para, idx) => (
            <p key={idx} className="mt-3 leading-relaxed text-foreground/85">
              {para}
            </p>
          ))}
        </div>
        <div
          className={`flex w-full flex-col items-center gap-3 ${
            reversed ? "md:order-1" : ""
          }`}
        >
          <PdfViewer key={book.pdf} src={book.pdf} height={420} />
          <p className="text-center text-sm text-foreground/60">
            [ {book.caption} ]
          </p>
          <a
            href={book.pdf}
            target="_blank"
            rel="noopener noreferrer"
            className={buttonVariants({ variant: "outline", size: "sm" })}
          >
            Open Full Screen ⤢
          </a>
        </div>
      </Card>
    </Reveal>
  );
}

function SectionDivider({ id, children }) {
  return (
    <Reveal as="div" id={id} className="my-4 text-center">
      <h2 className="font-[family-name:var(--font-display)] text-4xl font-bold text-foreground md:text-6xl">
        {children}
      </h2>
    </Reveal>
  );
}

export default function RocketPage() {
  return (
    <>
      <PageHero
        eyebrow="Rocket Science"
        title="Rocket"
        subtitle="Rocket science is the study and application of physics and engineering to design, build, and launch vehicles that travel through space."
        image="/Rocket/rc.webp"
      />

      <main className="mx-auto flex max-w-5xl flex-col gap-10 px-4 py-12 md:px-8">
        <Reveal>
          <Card
            variant="secondary"
            className="flex flex-col gap-6 p-6 md:flex-row md:justify-between md:p-8"
          >
            <div className="min-w-0 flex-1">
              <h2 className="text-2xl font-bold text-foreground md:text-3xl">
                About Rocket Science
              </h2>
              <p className="mt-3 leading-relaxed text-foreground/85">
                Rocket science is the study and application of the
                principles involved in launching and propelling rockets and
                spacecraft. It combines multiple disciplines, mainly
                aerospace engineering, physics, and mathematics, and it&rsquo;s
                often considered one of the most complex fields due to the
                extreme environments and precision required.
              </p>
            </div>
            <div className="flex flex-col gap-3 md:w-64 md:flex-none">
              {JUMP_LINKS.map((link) => (
                <a
                  key={link.href}
                  href={link.href}
                  className={buttonVariants({ variant: "outline" })}
                >
                  {link.label}
                </a>
              ))}
            </div>
          </Card>
        </Reveal>

        <Reveal delay={0.05}>
          <Card variant="secondary" className="p-6 md:p-8">
            <div className="mb-2 flex items-center gap-3">
              <Chip color="accent" variant="soft" size="sm">
                Quick Facts
              </Chip>
              <p className="text-sm text-foreground/60">
                Tap a topic to expand.
              </p>
            </div>
            <Accordion variant="surface" className="w-full">
              {QUICK_FACTS.map((fact) => (
                <Accordion.Item key={fact.title}>
                  <Accordion.Heading>
                    <Accordion.Trigger className="text-left text-base font-semibold text-foreground md:text-lg">
                      {fact.title}
                      <Accordion.Indicator />
                    </Accordion.Trigger>
                  </Accordion.Heading>
                  <Accordion.Panel>
                    <Accordion.Body className="leading-relaxed text-foreground/80">
                      {fact.body}
                    </Accordion.Body>
                  </Accordion.Panel>
                </Accordion.Item>
              ))}
            </Accordion>
          </Card>
        </Reveal>

        {/* <p className="text-center text-sm italic text-foreground/50">
          [ Note: You can read every Rocket Science book in pc mode ]
        </p> */}

        <SectionDivider id="RPB">Propulsion Basics</SectionDivider>
        {PROPULSION_BOOKS.map((book, i) => (
          <BookRow key={book.pdf} book={book} reversed={i % 2 === 1} />
        ))}

        <Reveal>
          <Card variant="secondary" className="flex flex-col items-center p-6 md:p-10">
            <video
              className="aspect-video w-full max-w-3xl rounded-2xl border border-[var(--border)]"
              src="/Rocket/Engine.mp4"
              aria-label="Engine Technology"
              controls
              preload="metadata"
            />
            <p className="mt-6 text-center text-2xl text-foreground">
              [ Engine Technology ]
            </p>
          </Card>
        </Reveal>

        <SectionDivider id="HR">Hybrid Rocket</SectionDivider>
        {HYBRID_BOOKS.map((book, i) => (
          <BookRow key={book.pdf} book={book} reversed={i % 2 === 1} />
        ))}

        <SectionDivider id="RSS">Rocket Science For Student&apos;s</SectionDivider>
        {STUDENT_BOOKS.map((book, i) => (
          <BookRow key={book.pdf} book={book} reversed={i % 2 === 1} />
        ))}
      </main>

      <BackToTop />

      <Footer />
    </>
  );
}
